 ;*******************************************************************************
;
;   Filename:	    Etch_a_sketch -> Principal.asm
;   Date:		    8/10/2020
;   File Version:	    v.1
;   Author:		    Noel Prado
;   Company:	    UVG
;   Description:	    Proyecto 2 etch a sketch
;
;*******************************************************************************  

    #include "p16f887.inc"

; CONFIG1
; __config 0xE0D5
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    GPR_VAR	    UDATA
DEL	    RES 1
NIBBLE_H	    RES 1
NIBBLE_L	    RES 1
BANDERAS    RES 1
STATUS_TEMP RES 1
 W_TEMP	    RES 1
NIBBLE_L2   RES 1
NIBBLE_H2   RES 1
 NIBBLE_L3   RES 1
NIBBLE_H3   RES 1
VAR_GENERAL1	RES 1
VAR_GENERAL2	RES 1
VAR_GENERAL3	RES 1
CANAL		RES 1
X_CEN		RES 1
X_DEC		RES 1
X_UNI		RES 1
Y_CEN		RES 1
Y_DEC		RES 1
Y_UNI		RES 1
CONTADOR	RES 1
ENTRADA		RES 1
CONTADOR2	RES 1
PIXEL_CEN	RES 1
PIXEL_DEC	RES 1
PIXEL_UNI		RES 1
PXH		RES 1
PXM		RES 1
PXL		RES 1
PYH		RES 1
PYM		RES 1
PYL		RES 1
DATO1		RES 1
DATO2		RES 1
DATO3		RES 1
DATOAUX		RES 1
	
		
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program
    
       
ISR_VECT    CODE 0X0004
    
PUSH:
    MOVWF	    W_TEMP
    SWAPF	   STATUS, W
    MOVWF	   STATUS_TEMP 

ISR:
    BTFSC INTCON,2  ;INTERRUPCION DEL TIMER 0
    GOTO    INT_TMR0
    BTFSC   PIR1,6 ;INTERRUPCION DEL ADC
    GOTO    INT_ADC
    BTFSC   PIR1,5   ;INTERRUPCION EUSART RECEIVER
    GOTO    INT_RC
    
INT_TMR0: ;MULTIPLEXACION DE LOS DISPLAYS
    BCF	INTCON,2
    MOVLW   VALOR_TMR0
    MOVWF   TMR0
    CALL MOSTRAR_DATOS
    INCF    MUX,F
    GOTO LOAD
INT_ADC:
    BCF	PIR1,6 ;SE LIMPIA LA BANDERA
    MOVF    ADRESH,W
    
    BTFSS   ADCON0,2 ;SI ESTE BIT ES CERO SE ESTABA LEYENDO EL CANAL 3
    GOTO LECTURA_C1
    
    MOVWF ADC_C1
    BCF	ADCON0,2 ;SE CAMBIA AL CANAL 1
    GOTO    FINAL
    
    LECTURA_C1
    MOVWF   ADC_C0
    BSF	ADCON0,2 ;SE CAMBIA AL CANAL 0
    
    FINAL
    NOP
    NOP
    NOP
    NOP
    NOP ;REQUERIMIENTOS DE ADQUISICION
    BSF	ADCON0,1 ;INICIA LA CONVERSION
    GOTO LOAD
INT_RC:
    MOVF    RCREG,W
    MOVWF   DATOAUX
    ;AQUI SE VERIFICA A QUE DATO CORRESPONDE
    MOVLW   .44 ;SE VERIFICA SI ES UNA COMA
    SUBWF   DATOAUX,W ;SI DA CERO ES QUE SE RECIBIO UNA COMA
    BTFSS   STATUS,2 ;BIT Z SI LO ANTERIOR DA CERO ES QUE SE LEYO UNA COMA
    GOTO    VER_Y
    
    ;SE LE LEYO UNA COMA SE EJECUTA ESTO
    CLRF    CONTADOR_RECEIVER
    MOVF    DATO1,W
    MOVWF  PIXEL_X_HIGH
    MOVF   DATO2,W
    MOVWF   PIXEL_X_MID
    MOVF    DATO3,W
    MOVWF   PIXEL_X_LOW
    GOTO LOAD ;SE SALE DE LA INTERRUPCION
    
    VER_Y
    MOVLW   .0
    SUBWF   DATOAUX,W
    BTFSS   STATUS,2 ;SI DA CERO, SE ENVIO EL CARACTER NULO, QUE INDICA QUE LOS VALORES ANTERIORES ERAN LOS CORRESPONDIENTES A Y
    GOTO    GUARDAR_COORDENADAS
    ;SE GUARDAN LOS VALORES DE Y
    CLRF    CONTADOR_RECEIVER
    MOVF    DATO1,W
    MOVWF  PIXEL_Y_HIGH
    MOVF   DATO2,W
    MOVWF  PIXEL_Y_MID
    MOVF    DATO3,W
    MOVWF  PIXEL_Y_LOW
    GOTO LOAD
    ;SE VAN GUARDANDO LOS DATOS
    GUARDAR_COORDENADAS
    MOVF    CONTADOR_RECEIVER,W
    ADDWF   PCL,F 
    GOTO VALOR1
    GOTO VALOR2
    GOTO VALOR3
    CLRF    CONTADOR_RECEIVER
    VALOR1
    MOVLW   .48
    SUBWF   DATOAUX,W
    MOVWF   DATO1
    INCF    CONTADOR_RECEIVER,F
    GOTO LOAD	
    VALOR2
    MOVLW   .48
    SUBWF   DATOAUX,W
    MOVWF   DATO2
    INCF    CONTADOR_RECEIVER,F
    GOTO LOAD	
    VALOR3
    MOVLW   .48
    SUBWF   DATOAUX,W
    MOVWF   DATO3
    INCF    CONTADOR_RECEIVER,F
   
    
    
LOAD:
    SWAPF   STATUS_RAM,W
    MOVWF   STATUS
    SWAPF   W_RAM,F
    SWAPF   W_RAM,W
    
    RETFIE

 TABLE
    ANDWF   B'00001111'; LIMITANDO DE 0 A F
    ADDWF   PCL, F
    ;	  PBAFGECD
    RETLW   B'01110111'	;0
    RETLW   B'01000010'	;1
    RETLW   B'01101101'	;2
    RETLW   B'01101011'	;3
    RETLW   B'01011010'	;4
    RETLW   B'00111011'	;5
    RETLW   B'00111111'	;6
    RETLW   B'01100010'	;7
    RETLW   B'01111111'	;8
    RETLW   B'01111011'	;9
    RETLW   B'01111110'	;A
    RETLW   B'00011111'	;B
    RETLW   B'00110101'	;C
    RETLW   B'01001111'	;D
    RETLW   B'00111101'	;E
    RETLW   B'00111100'	;F
    RETURN

MAIN_PROG CODE                      ; let linker place main program
 
START
 
    CALL	CONFIG_IO   
    CALL	CONFIG_INTERRUPT
 
LOOP:
    CLRF    X_CEN
    CLRF    X_DEC
    CLRF    X_UNI
    CLRF    Y_CEN
    CLRF    Y_DEC
    CLRF    Y_UNI
    
    
    CALL    DELAY
    LECTURA:
    BTFSS   ADCON0, GO
    BSF	ADCON0,GO		;INICIAR LA CONVERSION
    INCF	CONTADOR
    MOVLW .2
    SUBWF   CONTADOR
    BTFSS   STATUS, Z 
    GOTO    LECTURA
    
    CLRF    CONTADOR
    
   ;antes de mandar el código hay que hacer la conversión
XCENTENAS:
    MOVLW   .100
    SUBWF   VAR_GENERAL1, W
    BTFSC    STATUS, C
    MOVWF    VAR_GENERAL1
    BTFSC   STATUS, C
    INCF	X_CEN, F  
    BTFSC	STATUS, C
    GOTO XCENTENAS
   
XDECENAS:
    MOVLW    .10
    SUBWF   VAR_GENERAL1, W
    BTFSC    STATUS, C
    MOVWF    VAR_GENERAL1
    BTFSC   STATUS, C
    INCF	X_DEC, F
    BTFSC	STATUS, C
    GOTO XDECENAS
    
XUNIDADES:
    MOVLW    .1
    SUBWF   VAR_GENERAL1, W
    BTFSC    STATUS, C
    MOVWF    VAR_GENERAL1
    BTFSC   STATUS, C
    INCF	X_UNI, F
    BTFSC	STATUS, C
    GOTO XUNIDADES    

YCENTENAS:
    MOVLW   .100
    SUBWF   VAR_GENERAL2, W
    BTFSC    STATUS, C
    MOVWF    VAR_GENERAL2
    BTFSC   STATUS, C
    INCF	Y_CEN, F  
    BTFSC	STATUS, C
    GOTO YCENTENAS
   
YDECENAS:
    MOVLW    .10
    SUBWF   VAR_GENERAL2, W
    BTFSC    STATUS, C
    MOVWF    VAR_GENERAL2
    BTFSC   STATUS, C
    INCF	Y_DEC, F  
    BTFSC	STATUS, C
    GOTO YDECENAS
    
YUNIDADES:
    MOVLW    .1
    SUBWF   VAR_GENERAL2, W
    BTFSC    STATUS, C
    MOVWF    VAR_GENERAL2
    BTFSC   STATUS, C
    INCF	Y_UNI, F  
    BTFSC	STATUS, C
    GOTO YUNIDADES    
       
  ;despues de hacer la conversion para mandar centenas, decenas y unidades, tengo que sumarles 48 para que correspondan a numeros en ascii

     CALL	SEPARAR_NIBBLE
     CALL	DISPLAY
  
    MOVLW	.48
    ADDWF	X_CEN, F
    MOVLW	.48
    ADDWF	X_DEC, F
    MOVLW	.48
    ADDWF	X_UNI, F
    MOVLW	.48
    ADDWF	Y_CEN, F
    MOVLW	.48
    ADDWF	Y_DEC, F
    MOVLW	.48
    ADDWF	Y_UNI, F
  
   
    MOVF	    X_CEN, W
    MOVWF	    TXREG
    BTFSS	    PIR1, TXIF
    GOTO	    $-1
    CALL	DELAY
    
    MOVF	    X_DEC, W
    MOVWF	    TXREG
    BTFSS	    PIR1, TXIF
    GOTO	    $-1
    CALL	DELAY
    
    MOVF	    X_UNI, W
    MOVWF	    TXREG
    BTFSS	    PIR1, TXIF
    GOTO	    $-1
    CALL	DELAY
    
    MOVLW   B'00101100'    ;COMA
    MOVWF   TXREG
    BTFSS   PIR1, TXIF
    GOTO $-1
    CALL    DELAY
    CALL    DELAY
    CALL    DELAY
    
    MOVF	    Y_CEN, W
    MOVWF	    TXREG
    BTFSS	    PIR1, TXIF
    GOTO	    $-1
    CALL	DELAY
        
    MOVF	    Y_DEC, W
    MOVWF	    TXREG
    BTFSS	    PIR1, TXIF
    GOTO	    $-1
    CALL	DELAY

    MOVF	    Y_UNI, W
    MOVWF	    TXREG
    BTFSS	    PIR1, TXIF
    GOTO	    $-1
    CALL	DELAY
    
    MOVLW   B'00001010'	;NUEVA LINEA
    MOVWF   TXREG
    BTFSS   PIR1, TXIF
    GOTO $-1
    CALL    DELAY
    
    
    
    
    
    GOTO LOOP
    GOTO $                          ; loop forever
    
    
        
;***********************************************************SUBRUTINAS* *****************************************************************
     
    
        SEPARAR_NIBBLE
	
    MOVF    X_CEN, W
    MOVWF  NIBBLE_L
    
    MOVF    X_DEC, W
    MOVWF  NIBBLE_H
    
    MOVF    X_UNI, W
    MOVWF  NIBBLE_L2
    
    
    MOVF    Y_CEN, W
    MOVWF  NIBBLE_H2
    
    MOVF    Y_DEC, W
    MOVWF  NIBBLE_L3
    
    MOVF    Y_UNI, W
    MOVWF  NIBBLE_H3
    
    
   
    RETURN
    
    ;SE UTILIZA PARA VER QUE DISPLAY SE PRENDERA, VARIANDO VALOR DE BANDERAS CONTINUAMENTE 
TOGGLE_B0
    INCF   BANDERAS, F
    MOVLW    .6
    SUBWF    BANDERAS, W
    BTFSC    STATUS, Z 
    CLRF	BANDERAS
    RETURN   
    
      DISPLAY	    
    CLRF    PORTB
    MOVLW   .0
    SUBWF   BANDERAS,W
    BTFSC   STATUS, Z
    GOTO    DISPLAY_0
    MOVLW   .1
    SUBWF   BANDERAS, W
    BTFSC   STATUS, Z 
    GOTO DISPLAY_1
    MOVLW   .2
    SUBWF   BANDERAS,W
    BTFSC   STATUS, Z
    GOTO    DISPLAY_2
    MOVLW   .3
    SUBWF   BANDERAS, W
    BTFSC   STATUS, Z 
    GOTO  DISPLAY_3
    MOVLW   .4
    SUBWF   BANDERAS,W
    BTFSC   STATUS, Z
    GOTO    DISPLAY_4
    MOVLW   .5
    SUBWF   BANDERAS, W
    BTFSC   STATUS, Z 
    GOTO  DISPLAY_5
    
DISPLAY_0:
    MOVF  NIBBLE_L, W
    CALL	  TABLE
    MOVWF   PORTD
    BSF	    PORTB, RB0
    GOTO	 FIN_DISPLAY
DISPLAY_1:
    MOVF    NIBBLE_H, W	
    CALL    TABLE
    MOVWF   PORTD
    BSF	    PORTB, RD1
    GOTO	 FIN_DISPLAY
DISPLAY_2:
    MOVF    NIBBLE_L2, W
    CALL	TABLE
    MOVWF   PORTD
    BSF	PORTB, RB2
    GOTO    FIN_DISPLAY  
DISPLAY_3:
    MOVF    NIBBLE_H2, W
    CALL	TABLE
    MOVWF   PORTD
    BSF	PORTB, RB3
    GOTO	 FIN_DISPLAY
DISPLAY_4:
    MOVF    NIBBLE_L3, W
    CALL	TABLE
    MOVWF   PORTD
    BSF	PORTB, RB4
    GOTO    FIN_DISPLAY  
DISPLAY_5:
    MOVF    NIBBLE_H3, W
    CALL	TABLE
    MOVWF   PORTD
    BSF	PORTB, RB5
    GOTO	 FIN_DISPLAY
FIN_DISPLAY:
    CALL    TOGGLE_B0
    RETURN
    
    
    DELAY
    MOVLW   .255
    MOVWF   DEL
    DECFSZ  DEL, F
    GOTO    $-1
    RETURN

    
;***************************************************CONFIGURACIONES *****************************************************************
    CONFIG_IO
  
    BANKSEL	TRISA
    CLRF		TRISB
    CLRF		TRISD
    MOVLW		B'11111111'
    MOVWF		TRISC
    
    BANKSEL	PORTA
    CLRF		PORTA
    CLRF		PORTC
    CLRF		PORTD
    CLRF		PORTB
    CLRF		NIBBLE_H
    CLRF		NIBBLE_L
    
    CLRF		CANAL
    CLRF		VAR_GENERAL1
    CLRF		VAR_GENERAL2
    CLRF		PXH
    CLRF		PXM
    CLRF		PXL
    CLRF		PYH
    CLRF		PYM
    CLRF		PYL


    BANKSEL ADCON1
    MOVLW B'00000000' ; JUSTIFICADO A LA IZQUIERDA
    MOVWF ADCON1	   ; VDD COMO REFER ENCIA
    BANKSEL TRISA
    BSF	TRISA, 0
    BSF	TRISA, 1
    BANKSEL ANSEL
    BSF	ANSEL, 0
    BSF	ANSEL, 1
    BANKSEL ADCON0
    MOVLW B'01000001'	;FOSC/8
    MOVWF ADCON0		;AN0, On
    
    BANKSEL TRISA
    MOVLW   .25	;PARA BAUDRATE DE 9615
    MOVWF    SPBRG
    CLRF    SPBRGH  

    BSF	TXSTA, BRGH ; HIGH SPEED DE BAUDIOS
    BCF	TXSTA, SYNC;MODO ASINCRONO
    BSF	TXSTA, TXEN; SE HABILITA LA TRANSMISION
    BCF	TXSTA, TX9 ; SOLO 8 BITS
    BANKSEL BAUDCTL
    BCF	BAUDCTL, BRG16 ;SE USAN 8 BITS
    
    BANKSEL PORTA
    BSF	RCSTA, SPEN ;PARA QUE LA SALIDA SEA EN TX   
    BSF	RCSTA, CREN;PARA QUE LA ENTRADA SEA EN RX
    RETURN
    
    
     CONFIG_INTERRUPT
    
    BANKSEL	TRISA
    BSF		PIE1, ADIE
    BSF		PIE1, RCIE
    BANKSEL	PORTA
    BSF		INTCON, GIE
    BSF		INTCON, PEIE
    BCF		PIR1, ADIF

    RETURN

    END